# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7984e2bae00f03f374cd8b68cf9016091f880e14971927ec8cc33f38e128f47ac258c81a1ffcd5ca4443041c169241d5b38d419204ba5c7367e34272ab3a9502

test:
  secret_key_base: 58f71b96e0806c759b9801eae850e3736af22958fc3784b2858d2981b3cad977e753acba82cee60a1e8a1e0b2c261cb941924c9d1520fcb68e06823843fb2ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
